### ISSUE TITLE
Hi @vhnatyk I need to create wasm files in zengo_mpc_eddsa code. Please help me in that. I am not able to create wasm files.

### ISSUE THREAD

**Issue by dheeraj-721** [vhnatyk/emerald-city#5]
Hi @vhnatyk I need to create wasm files in zengo_mpc_eddsa code. Please help me in that. I am not able to create wasm files.

Thanks

_Originally posted by @dheeraj-721 in https://github.com/vhnatyk/emerald-city/issues/2#issuecomment-1581305343_

**Comment by vhnatyk** [comment]
Hi - uh oh, was so long time ago  - I don't remember the command line or exact environment settings for wasm unfortunately

**Comment by dheeraj-721** [comment]
Can you please give me any reference from where I can follow those steps?
It can help me because when I'm creating wasm file, It's giving a lots of
errors like below -

"error[E0599]: no method named `as_sock` found for reference `&TcpBuilder`
> in the current scope
>     -->
> /Users/dheerajkumar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/net2-0.2.39/src/ext.rs:1407
> :22
>      |
> 1407 |         set_opt(self.as_sock(), SOL_SOCKET, SO_REUSEADDR,
>      |                      ^^^^^^^ method not found in `&TcpBuilder`
>      |
>      = help: items from traits can only be used if the trait is
> implemented and in scope
> note: `AsSock` defines an item `as_sock`, perhaps you need to implement it
>     -->
> /Users/dheerajkumar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/net2-0.2.39/src/ext.rs:650
> :1
>      |
> 650  | pub trait AsSock {
>      | ^^^^^^^^^^^^^^^^


> error[E0599]: no method named `as_sock` found for reference `&TcpBuilder`
> in the current scope
>     -->
> /Users/dheerajkumar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/net2-0.2.39/src/ext.rs:1413
> :22
>      |
> 1413 |         get_opt(self.as_sock(), SOL_SOCKET,
> SO_REUSEADDR).map(int2bool)
>      |                      ^^^^^^^ method not found in `&TcpBuilder`
>      |
>      = help: items from traits can only be used if the trait is
> implemented and in scope
> note: `AsSock` defines an item `as_sock`, perhaps you need to implement it
>     -->
> /Users/dheerajkumar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/net2-0.2.39/src/ext.rs:650
> :1
>      |
> 650  | pub trait AsSock {
>      | ^^^^^^^^^^^^^^^^


error[E0599]: no method named `as_sock` found for reference `&TcpBuilder`
> in the current scope
>     -->
> /Users/dheerajkumar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/net2-0.2.39/src/ext.rs:1422
> :22
>      |
> 1422 |         get_opt(self.as_sock(), SOL_SOCKET, SO_ERROR).map(int2err)
>      |                      ^^^^^^^ method not found in `&TcpBuilder`
>      |
>      = help: items from traits can only be used if the trait is
> implemented and in scope
> note: `AsSock` defines an item `as_sock`, perhaps you need to implement it
>     -->
> /Users/dheerajkumar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/net2-0.2.39/src/ext.rs:650
> :1
>      |
> 650  | pub trait AsSock {
>      | ^^^^^^^^^^^^^^^^


error[E0599]: no method named `as_sock` found for reference `&TcpBuilder`
> in the current scope"

error: could not compile `net2` (lib) due to 319 previous errors
